# [Lior Dux] ==================== [ GitHub Actions CI-CD Pipelien ] ====================  [14-02-2023] #
#
# Purpose:
# This workflow is meant to tag the image correctly, and push into AWS Elastic Container Registery.
#
# Actions plugibs used:
# 1) (checkout@v3)[https://github.com/marketplace/actions/checkout]
# 2) (aws-actions/configure-aws-credentials@v1)[https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions]
# 3) (aws-actions/amazon-ecr-login@v1)[https://github.com/marketplace/actions/amazon-ecr-login-action-for-github-actions]
# 4) (aws-actions/amazon-ecs-render-task-definition@v1)[https://github.com/marketplace/actions/amazon-ecs-render-task-definition-action-for-github-actions]
# 5) (aws-actions/amazon-ecs-deploy-task-definition@v1)[https://github.com/marketplace/actions/amazon-ecs-deploy-task-definition-action-for-github-actions]
#
name: Publish
on:
  workflow_call:
    # Reguired inputs
    inputs:
      environment:
        required: true
        type: string
      imageTag:
        required: true
        type: string
      containerName:
        required: false
        type: string
        default: "my-container"
      taskDefinitionContext:
        required: false
        type: string
        default: "./"
      taskDefinition:
        required: false
        type: string
        default: "task-definition.json"
      serviceName:
        required: false
        type: string
        default: "my-service"
      clusterName:
        required: false
        type: string
        default: "vsl-dev"

    # Required secrets
    secrets:
      AWS_REGION:
        required: true
      ECR_REGISTRY:
        required: true
      REPO_NAME:
        required: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read

    steps:
  
      - name: Git clone
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-session-name: GitHub-Actions-OIDC
          role-duration-seconds: 1200
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: TEST BEFORE ACTION
        working-directory: ${{ inputs.taskDefinitionContext }}
        run:  cat ${{ inputs.taskDefinitionContext }}/${{ inputs.taskDefinition }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        working-directory: ${{ inputs.taskDefinitionContext }}
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          # Do NOT put a '/' in between the ECR_REGISTRY and REPO_NAME here!!!
          image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.REPO_NAME }}:${{ inputs.imageTag }}
          task-definition: ${{ inputs.taskDefinition }}
          container-name: ${{ inputs.containerName }}

      - name: TEST AFTER RENDER ACTION
        run:  cat  ${{ steps.task-dep.outputs.task-definition }}

      - name: Deploy Amazon ECS task definition
        id: task-dep
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ inputs.serviceName }}
          cluster: ${{ inputs.clusterName }}
