# [Lior Dux] ==================== [ GitHub Actions CI-CD Pipelien ] ====================  [14-02-2023] #
#
# Purpose:
# This workflow is meant to run all unit-tests.
#
# Actions plugibs used:
# 1) (checkout@v3)[https://github.com/marketplace/actions/checkout]
# 2) (andymckay/cancel-action@0.3)[andymckay/cancel-action@0.2]
#
name: Test
on:
  workflow_call:
    # Reguired inputs
    inputs:
      DockerfileContext:
        required: true
        type: string
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v3

      - name: UnitTest#1
        working-directory: ${{ inputs.DockerfileContext }}
        run: |
          docker build -t pipeline:current-build-test2 -f Dockerfile .
          docker run --name dockertest1 -d pipeline:current-build-test2
          echo "Assume we have unit tests to run..."
          docker stop dockertest1

      - name: UnitTest#2
        working-directory: ${{ inputs.DockerfileContext }}
        run: |
          docker build -t pipeline:current-build-test2 -f Dockerfile .
          docker run --name dockertest2 -d pipeline:current-build-test2
          echo "Assume we have unit tests to run..."
          docker stop dockertest2

      - name: UnitTest#2
        working-directory: .${{ inputs.DockerfileContext }}
        run: |
          docker build -t pipeline:current-build-test2 -f Dockerfile .
          docker run --name dockertest3 -d pipeline:current-build-test2
          echo "Assume we have unit tests to run..."
          docker stop dockertest3

      - name: Cancelling workflow on error
        if: failure()
        uses: andymckay/cancel-action@0.2